create table if not exists public.evaluaciones (
  id bigint generated by default as identity primary key,
  nombre text not null,
  agudeza_visual text not null,
  campo_visual integer not null check (campo_visual between 0 and 180),
  tipo_vision text not null,
  nivel text not null,
  favorito boolean not null default false,
  completado boolean not null default false
);

alter table public.evaluaciones enable row level security;

grant all on table public.evaluaciones to service_role;
grant usage, select on sequence public.evaluaciones_id_seq to service_role;

insert into public.evaluaciones
  (id, nombre, agudeza_visual, campo_visual, tipo_vision, nivel, favorito, completado)
values
  (1, 'María López', '20/20', 120, 'Normal', 'Sin alteración', false, true),
  (2, 'Juan Pérez', '20/80', 95, 'Baja Visión', 'Leve', true, true),
  (3, 'Ana García', '20/200', 60, 'Baja Visión', 'Moderada', false, false),
  (4, 'Carlos Ruiz', '20/400', 25, 'Baja Visión', 'Severa', false, true),
  (5, 'Sofía Méndez', '20/600', 8, 'Ceguera', 'Parcial', true, false),
  (6, 'Luis Torres', '20/1000', 3, 'Ceguera', 'Casi total', false, true),
  (7, 'Elena Castro', 'Sin percepción', 0, 'Ceguera', 'Total', false, false),
  (8, 'Pedro Jiménez', '20/50', 105, 'Normal', 'Leve disminución', false, true)
on conflict (id) do nothing;

select setval(
  pg_get_serial_sequence('public.evaluaciones', 'id'),
  coalesce((select max(id) from public.evaluaciones), 1),
  true
);
